version: "3.9"
services:

  siderunner:
    container_name: siderunner
    build: .
    image: siderunner:v1
    environment:
      - PARAMETERS
      - TITLE
      # - TEMPLATE="traditional-html"
      - DESCRIPTION
      - SITES
      - REPORT_PATTERN=report
      - REPORT_DIR=/home/zap/report
      - ZAP_API_URL=http://zap:8090
      - PROXY_SERVER=zap:8090
      - CHROME_API_URL=http://chrome:4444/wd/hub
    volumes:
      - CURRENT_DIR/report:/report
    links:
      - chrome
      - zap
    depends_on:
      zap:
        condition: service_healthy
      chrome:
        condition: service_healthy
    networks:
      - zap_network

  chrome:
    container_name: chrome
    image: selenium/standalone-chrome:4.1.2-20220217
    healthcheck:
      test: curl --fail http://chrome:4444 || exit 1
      interval: 30s
      retries: 2
      start_period: 10s
      timeout: 5s
    expose:
      - "4444"
    links:
      - zap
    shm_size: '2gb'
    depends_on:
      - zap
    networks:
      - zap_network

  zap:
    container_name: zap
    user: "0:0"
    image: owasp/zap2docker-stable
    command: ["zap.sh", "-daemon", "-port", "8090", "-host", "0.0.0.0", "-config", "api.addrs.addr.name=.*", "-config", "api.addrs.addr.regex=true", "-config", "api.disablekey=true", "-config", "proxy.behindnat=true"]
    expose:
      - "8090"
    environment:
      - ZAP_PORT=8090
    volumes:
      - CURRENT_DIR/report:/home/zap/report
    networks:
      - zap_network

networks:
  zap_network:
    driver: bridge
